config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:new, :create]

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root "home#index"
  get "/home", to: "home#index"
  get "/profile", to: "home#profile"
  get "/profile/services", to: "home#profile_services"
  get "/coins", to: "home#coins", as: "coins"
  get "/paymenthistory", to:"home#payment_history", as: "payment_history"

  resources :services
  resources :trades, only: [:new, :create, :index, :update]
  get "/trades/archived", to: "trades#archived"

  resources :reviews, only: [:create]

end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :user
    has_many :trades

    validates_presence_of :name, :description, :category, :user_id, :region, :price
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def index
        @description = params[:description]
        @category = params[:category]
        @services = []
        if @description
            # filter to region selected on signup and match typed keywords with any string partials in description field
            @services = Service.where(region: current_user.region).where("description LIKE ?", "%#{@description}%")
            @services = "Sorry, there are no listings for #{@description} in your area." if @services.empty?
        elsif @category
            # filter listings by user region and selected category
            @services = Service.where(region: current_user.region, category: params[:category])
            @services = "Sorry, there are no listings for #{@category} in your area." if @services.empty?
        end
    end

    def create
        @service = Service.new(service_params)
        @service.user = current_user
        @service.region = current_user.region
        if @service.save!
          flash[:notice] = 'Service added successfully.'   
          redirect_to profile_services_path
        else
          @service.errors.messages
          flash[:alert] = 'Failed to add service.'   
          render :new       
        end    
    end

    def edit
        @service = Service.find(params[:id])
        authorize_user!(@service)
    end

    def update
        @service = Service.find(params[:id])
        authorize_user!(@service)
        if @service.update(service_params)
          flash[:notice] = 'Service updated successfully.'   
          redirect_to profile_services_path
        else
          flash[:alert] = 'Failed to update service.'
          render :edit
        end
    end

    protected
    def service_params
        params.require(:service).permit(:category, :name, :description, :price, :archived)
    end
end

app/views/services/edit.slim
= form_for @service, url: "/services/#{@service.id}", method: :patch do |f|
  .field 
    = f.label :category, "Category"
    = f.select :category, @lists.categories
  .field
    = f.label :name, "Title", style: "margin-top: 2vh;"
    = f.text_field :name
  .field
    = f.label :description, "Description"
    = f.text_field :description
  .field
    = f.label :price, "Price"
    = f.number_field :price
  .field 
    = f.label :archived, "Remove Listing?"
    = f.check_box :archived
  .field 
    = f.submit

app/views/services/index.slim
= render("searchbar")

h2 #{@description}#{@category} listings in #{current_user.region}

- if @services.is_a? String
  p #{@services}
- else
  - @services.each do |s|
    .service-container
      h3.service-title #{s.name}
      h4 Seller: #{s.user.name} - Rating: #{s.user.rating}
      p.service-body #{s.description}
      p.service-body Price: #{s.price} SkratchCoins
      .link-container
        = link_to "Purchase Service", new_trade_path(service_id: s.id)

app/views/services/new.slim
p #{flash.alert}

= form_for Service.new, url: services_path do |f|
  = hidden_field :archived, value: false
  .field 
    = f.label :category, "Category"
    = f.select :category, @lists.categories
  .field
    = f.label :name, "Title", style: "margin-top: 2vh;"
    = f.text_field :name
  .field
    = f.label :description, "Description"
    = f.text_field :description
  .field
    = f.label :price, "Price"
    = f.number_field :price
  .field 
    = f.submit