config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:new, :create]

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root "home#index"
  get "/home", to: "home#index"
  get "/profile", to: "home#profile"
  get "/profile/services", to: "home#profile_services"
  get "/coins", to: "home#coins", as: "coins"
  get "/paymenthistory", to:"home#payment_history", as: "payment_history"

  resources :services
  resources :trades, only: [:new, :create, :index, :update]
  get "/trades/archived", to: "trades#archived"

  resources :reviews, only: [:create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def payment_history
        # find and list successful payments
        @payments = current_user.payments.where successful: true
    end

    def profile_services
        @services = current_user.services.where(archived: false) 
    end
end

app/helpers/home_helper.rb
module HomeHelper
    def add_services_path
        return profile_services_path if current_user.first_name && current_user.region

        flash[:alert] = 'Please complete your profile before using Skratch.'
        edit_user_registration_path
    end
end

app/views/home/coins.slim
h2 Add Balance

- [20, 50, 100, 250].each do |n|
  .link-container
    = link_to "Buy #{n} Skratchcoins for $#{n} AUD", new_payment_path(amount: n)

app/views/home/index.slim
h1.instruction Search for a service:

= render "searchbar"

h1.instruction Or browse categories:

.navlist 
  - @lists.categories.each do |cat|
    .category
      = link_to(cat, services_path(category: cat))

app/views/home/payment_history.slim
h2 Payment History 

- if @payments.empty?
  p No payments recorded yet.
  .link-container
    = link_to "Buy SkratchCoins", coins_path
- else
  table
    tr 
      th Date 
      th Amount
    - @payments.each do |payment|
      tr 
        td #{I18n.l(payment.created_at, format: :long)}
        td #{number_to_currency(payment.amount.to_i / 100)}

app/views/home/profile.slim
= render "avatar" 
p.bold
  - if current_user.first_name && current_user.region
    = "Welcome back, #{current_user.first_name}"
  - else
    = "Please complete your profile."
p Current Balance: #{current_user.balance.balance} SkratchCoins
.category
  = link_to("Buy SkratchCoins",    coins_path)
.category 
  = link_to("Payment History",     payment_history_path)
.category
  = link_to("Edit profile",        edit_user_registration_path)
.category   
  = link_to("Add/update services", add_services_path)
.category
  = link_to("View trades",         trades_path)
.category
  = link_to("Sign out",            destroy_user_session_path, method: :delete)

app/views/home/profile_services.slim
h2 Add/Update Services

- @services.each do |s|
  .service-container
    h3.service-title #{s.name}
    p #{s.description}
    p Price: #{s.price} SkratchCoins
    .link-container
      = link_to "Edit Listing", "/services/#{s.id}/edit"

.link-container
  = link_to "List a Service", new_service_path