config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:new, :create]

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root "home#index"
  get "/home", to: "home#index"
  get "/profile", to: "home#profile"
  get "/profile/services", to: "home#profile_services"
  get "/coins", to: "home#coins", as: "coins"
  get "/paymenthistory", to:"home#payment_history", as: "payment_history"

  resources :services
  resources :trades, only: [:new, :create, :index, :update]
  get "/trades/archived", to: "trades#archived"

  resources :reviews, only: [:create]

end

app/controllers/application_controller.rb
require_relative "concerns/lists"

class ApplicationController < ActionController::Base
    attr_reader :regions, :categories
    before_action :authenticate_user!

    def initialize
        super
        @lists = Lists.new
    end
    
    def authorize_user!(model)
        return if model.user_id == current_user.id

        flash[:alert] = 'You do not have permission to access that page.'
        redirect_to root_path and return
    end

    def seller
        User.find(id: self.seller_id)
    end
end

app/views/application/_avatar.slim
- if user_signed_in? && current_user.avatar
  img.navbtn src="#{current_user.avatar}"
- else
  = image_tag("avatar.png", :class => "navbtn")

app/views/application/_back.slim
.link-container
  = link_to "Back", "javascript:history.back()"

app/views/application/_header.slim
header.navbar
  = link_to(root_path) do
    .label-container
      #home-button.bold 🏠
      span Home
  = link_to(root_path) do 
    = image_tag("logo.png", :id => "logo", :alt => "logo")
  = link_to(profile_path) do
    .label-container
      = render "avatar"
      span View Profile

app/views/application/_searchbar.slim
= form_with url: services_path, method: :get do |f|
  .searchbar
    = f.text_field :description
    = f.submit '🔍', id: 'keywords-submit'